# Generated by Django 4.2.3 on 2023-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="test_f",
            field=models.CharField(default="", max_length=255),
        ),
    ]
